version: "3.4"
services:
  postgres:
    container_name: todo-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: db_pass
volumes:
  pg_data:
